import { Metadata } from "next";
import MenuExplorer from "@/components/menu-explorer";
import { MenuItem } from "@/components/menu-card";

export const metadata: Metadata = {
  title: "Our Menu - Seasonal Brunch & Dinner | Town Tonic Christchurch",
  description: "Browse the Town Tonic digital menu. Sourced from organic Canterbury farms, we serve fresh brunch, dinner mains, and local craft drinks in Addington.",
};

const MENU_ITEMS: MenuItem[] = [
  // ALL DAY BRUNCH (from PDF & original items)
  {
    id: "b1",
    name: "Mr. Simple",
    price: 21.00,
    description: "Sourdough toast with smashed avocado, pumpkin seeds, toasted nuts, heirloom tomato, and house pickled red onions.",
    category: "brunch",
    subCategory: "honest",
    tags: ["Vegan", "Vegetarian", "Dairy-Free"],
    image: "/images/hero_brunch.jpg",
  },
  {
    id: "b2",
    name: "Honey Glazed Haloumi",
    price: 25.50,
    description: "Toast with avocado, organic mix greens, tomatoes, fresh chili, honey glazed haloumi, seeds, and sweet balsamic glaze.",
    category: "brunch",
    subCategory: "honest",
    tags: ["Vegetarian"],
    image: "/images/gallery_coffee.jpg",
  },
  {
    id: "b3",
    name: "Mr. Funghi",
    price: 22.00,
    description: "Sourdough toast topped with market mix mushrooms, baby spinach, garlic cream, and rich truffle essence.",
    category: "brunch",
    subCategory: "honest",
    tags: ["Vegetarian"],
    image: "/images/gallery_interior.jpg",
  },
  {
    id: "b4",
    name: "Crispy Lentil Fritters",
    price: 21.90,
    description: "Crispy fried lentil fritters, beetroot hummus, mix greens, fresh jalapeno salsa, roasted seeds, and sumac.",
    category: "brunch",
    subCategory: "honest",
    tags: ["Vegan", "Vegetarian", "Gluten-Free", "Dairy-Free"],
    image: "/images/about_suppliers.jpg",
  },
  {
    id: "b5",
    name: "Eggbert Einstein",
    price: 16.00,
    description: "Two eggs prepared any way you like, rich sundried tomato pesto, and toasted sourdough. Add crispy bacon for $6.00.",
    category: "brunch",
    subCategory: "eggs",
    tags: ["Vegetarian"],
    image: "/images/hero_brunch.jpg",
  },
  {
    id: "b6",
    name: "Country Style Grits",
    price: 23.00,
    description: "Creamy polenta grits served with pork sausages, fried farm eggs, slow-braised red cabbage, and rich gravy.",
    category: "brunch",
    subCategory: "eggs",
    tags: [],
    image: "/images/gallery_dinner.jpg",
  },
  {
    id: "b7",
    name: "Omelettina",
    price: 24.00,
    description: "Fluffy three-egg omelette stuffed with baby spinach, market mushrooms, cheddar cheese, and served with toast.",
    category: "brunch",
    subCategory: "eggs",
    tags: ["Vegetarian"],
    image: "/images/gallery_coffee.jpg",
  },
  {
    id: "b8",
    name: "Silky Shell",
    price: 24.00,
    description: "Soft flour tortillas, fried eggs, fresh avocado, crispy bacon, house jalapeno salsa, and toasted seeds.",
    category: "brunch",
    subCategory: "eggs",
    tags: ["Dairy-Free"],
    image: "/images/gallery_interior.jpg",
  },
  {
    id: "b9",
    name: "Poultry Poet",
    price: 26.50,
    description: "Perfectly poached eggs on a classic muffin, with chili hollandaise and mix greens. Choose from: bacon, mushrooms, fried chicken, or smoked salmon.",
    category: "brunch",
    subCategory: "eggs",
    tags: [],
    image: "/images/hero_brunch.jpg",
  },
  {
    id: "b10",
    name: "Egg-Centric",
    price: 30.50,
    description: "The ultimate big breakfast: two eggs any style, crispy bacon, grilled tomato, market mushrooms, sausage, and golden hash browns.",
    category: "brunch",
    subCategory: "eggs",
    tags: [],
    image: "/images/gallery_dinner.jpg",
  },
  {
    id: "b11",
    name: "French Toast",
    price: 24.50,
    description: "Thick-cut french toast served with mixed berry compote, sweet vanilla cream, pure maple syrup, and dusted with icing sugar.",
    category: "brunch",
    subCategory: "eggs",
    tags: ["Vegetarian"],
    image: "/images/gallery_coffee.jpg",
  },
  {
    id: "b12",
    name: "Beetroot and Feta Salad",
    price: 24.00,
    description: "Mix greens tossed with roasted seeds, nuts, fresh cucumber, tomatoes, sweet sultanas, creamy feta, and balsamic vinaigrette.",
    category: "brunch",
    subCategory: "lunch",
    tags: ["Vegetarian", "Gluten-Free"],
    image: "/images/about_suppliers.jpg",
  },
  {
    id: "b13",
    name: "Bang Bang Chicken",
    price: 27.50,
    description: "Crispy buttermilk fried chicken, gochujang kewpie, fresh chili, house kimchi, mix greens, and crunchy crushed peanuts.",
    category: "brunch",
    subCategory: "lunch",
    tags: [],
    image: "/images/gallery_dinner.jpg",
  },
  {
    id: "b14",
    name: "TT Braised Beef Cheeks",
    price: 34.90,
    description: "Tender, slow-braised beef cheeks served with beetroot hummus, house kimchi, two fried eggs, and spicy chili hollandaise.",
    category: "brunch",
    subCategory: "lunch",
    tags: ["Gluten-Free"],
    image: "/images/gallery_interior.jpg",
  },
  {
    id: "b15",
    name: "Keto Steak and Eggs",
    price: 33.00,
    description: "Two farm eggs prepared any style, rich avocado butter, mix greens, and seasonal Canterbury vegetables.",
    category: "brunch",
    subCategory: "lunch",
    tags: ["Gluten-Free"],
    image: "/images/gallery_dinner.jpg",
  },
  {
    id: "b16",
    name: "Fish of the Day",
    price: 32.00,
    description: "Ask your server for today's daily creation, freshly caught and styled with seasonal garnishes.",
    category: "brunch",
    subCategory: "lunch",
    tags: ["Gluten-Free"],
    image: "/images/gallery_dinner.jpg",
  },
  {
    id: "b17",
    name: "Pappardelle Funghi",
    price: 29.00,
    description: "Wild Canterbury mushrooms, baby spinach, grana padano, shaved almonds, and fresh garden herbs.",
    category: "brunch",
    subCategory: "lunch",
    tags: ["Vegetarian"],
    image: "/images/gallery_coffee.jpg",
  },
  {
    id: "b18",
    name: "Loaded Open Faced Sandwich",
    price: 30.00,
    description: "Toasted open sandwich with melted cheese, mix greens, pickles, avocado, gochujang mayo, and mustard, served with fries. Choose: fried chicken or sirloin. Add fried egg: $3.",
    category: "brunch",
    subCategory: "lunch",
    tags: [],
    image: "/images/gallery_interior.jpg",
  },

  // DINNER MAINS
  {
    id: "d1",
    name: "Five Course Tasting Menu",
    price: 105.00,
    description: "Our signature chef's selection tasting menu, highlighting the best seasonal Canterbury ingredients. Trust the chef to amaze your palate.",
    category: "dinner",
    subCategory: "tasting",
    tags: [],
    image: "/images/gallery_dinner.jpg",
  },
  {
    id: "d2",
    name: "Five Course Plant-Based Menu",
    price: 85.00,
    description: "A complete five-course tasting menu focused entirely on seasonal plants, Canterbury soil produce, and creative gastronomy techniques.",
    category: "dinner",
    subCategory: "tasting",
    tags: ["Vegan", "Vegetarian", "Dairy-Free"],
    image: "/images/about_suppliers.jpg",
  },
  {
    id: "d3",
    name: "Baby Carrots",
    price: 22.00,
    description: "Canterbury baby carrots glazed in savory teriyaki sauce, topped with toasted sesame seeds and crunchy fried garlic.",
    category: "dinner",
    subCategory: "growers",
    tags: ["Vegan", "Vegetarian", "Dairy-Free"],
    image: "/images/about_suppliers.jpg",
  },
  {
    id: "d4",
    name: "Clearwater Greens",
    price: 17.00,
    description: "Fresh Clearwater greens tossed with crisp apple slices, shaved fennel, spiced crispy chickpeas, toasted seeds, and our signature green goodness dressing.",
    category: "dinner",
    subCategory: "growers",
    tags: ["Vegan", "Vegetarian", "Gluten-Free", "Dairy-Free"],
    image: "/images/about_suppliers.jpg",
  },
  {
    id: "d5",
    name: "Grilled Broccoli",
    price: 21.00,
    description: "Char-grilled broccoli florets served over rich cashew satay sauce, finished with chili oil, toasted quinoa, and fresh Addington herbs.",
    category: "dinner",
    subCategory: "growers",
    tags: ["Vegan", "Vegetarian", "Gluten-Free", "Dairy-Free"],
    image: "/images/gallery_interior.jpg",
  },
  {
    id: "d6",
    name: "Twice Cooked Golden Potatoes",
    price: 17.00,
    description: "Twice-cooked golden gourmet potatoes, topped with creamy bacon bearnaise, shaved grana padano, and fresh garden herbs.",
    category: "dinner",
    subCategory: "growers",
    tags: ["Gluten-Free"],
    image: "/images/gallery_dinner.jpg",
  },
  {
    id: "d7",
    name: "Wairiri Burrata",
    price: 30.00,
    description: "Cold smoked Wairiri burrata cheese served with a vibrant citrus salad, dark olive crumble soil, beetroot veil, and fresh basil oil.",
    category: "dinner",
    subCategory: "growers",
    tags: ["Vegetarian", "Gluten-Free"],
    image: "/images/gallery_coffee.jpg",
  },
  {
    id: "d8",
    name: "Raw Fish Salad",
    price: 29.00,
    description: "Ethically harvested raw fish tossed with cucumber, shallots, sweet pineapple, fresh lemon, coriander, coconut cream, and crispy sesame bark.",
    category: "dinner",
    subCategory: "seafood",
    tags: ["Gluten-Free", "Dairy-Free"],
    image: "/images/gallery_dinner.jpg",
  },
  {
    id: "d9",
    name: "Pan Fried Fish of the Day",
    price: 48.00,
    description: "Pan-fried wild caught fish, Cloudy Bay clams, gourmet potatoes, chorizo, seasonal Canterbury vegetables, salsa vierge sauce, and crispy capers.",
    category: "dinner",
    subCategory: "seafood",
    tags: ["Gluten-Free"],
    image: "/images/gallery_dinner.jpg",
  },
  {
    id: "d10",
    name: "Crispy Seasoned Squid",
    price: 27.00,
    description: "Seasoned crispy squid served with shaved fennel, wasabi cream, charred lemon, and a dusting of leek ash.",
    category: "dinner",
    subCategory: "seafood",
    tags: ["Dairy-Free"],
    image: "/images/gallery_dinner.jpg",
  },
  {
    id: "d11",
    name: "Seared Scallops",
    price: 36.00,
    description: "Pan-seared wild scallops served over edamame & miso puree, with fresh radish, puffed sago, cuttlefish emulsion, and premium caviar.",
    category: "dinner",
    subCategory: "seafood",
    tags: ["Gluten-Free"],
    image: "/images/gallery_dinner.jpg",
  },
  {
    id: "d12",
    name: "Bang Bang Chicken (Dinner)",
    price: 29.00,
    description: "Crispy buttermilk fried chicken, house-made kimchi, gochujang kewpie, chili honey, togarashi spices, and crushed peanuts.",
    category: "dinner",
    subCategory: "meat",
    tags: [],
    image: "/images/gallery_dinner.jpg",
  },
  {
    id: "d13",
    name: "Sous Vide Beef Fillet",
    price: 59.00,
    description: "Sous vide beef fillet, carrot veloute, Addington fresh chimichurri, baby carrots, potato espuma, braised pearl onion, pressed beef cheek, and rich au jus.",
    category: "dinner",
    subCategory: "meat",
    tags: ["Gluten-Free"],
    image: "/images/gallery_dinner.jpg",
  },
  {
    id: "d14",
    name: "Sous Vide Lamb Rump",
    price: 57.00,
    description: "Sous vide lamb rump, spinach & green pea puree, hasselback gourmet potatoes, tzatziki, spicy harissa, blistered cherry tomatoes, goat cheese bon bon, and hazelnut chermoula.",
    category: "dinner",
    subCategory: "meat",
    tags: ["Gluten-Free"],
    image: "/images/gallery_dinner.jpg",
  },
  {
    id: "d15",
    name: "Sous Vide Venison Loin",
    price: 55.00,
    description: "Sous vide venison loin rubbed in coffee & star anise, carrot veloute, braised kale, blackberry, beetroot ketchup, chili chocolate reduction, and beet dust.",
    category: "dinner",
    subCategory: "meat",
    tags: ["Gluten-Free"],
    image: "/images/gallery_dinner.jpg",
  },
  {
    id: "d16",
    name: "Braised Beef Cheeks (Dinner)",
    price: 55.00,
    description: "Tender beef cheeks braised in Cassels stout, served with kumara mash, parsnip textures, garden herb oil, and sweet-sour agrodolce.",
    category: "dinner",
    subCategory: "meat",
    tags: [],
    image: "/images/gallery_dinner.jpg",
  },

  // DRINKS & ELIXIRS
  {
    id: "dr1",
    name: "Single Origin Batch Brew",
    price: 6.00,
    description: "Artisan filter brew sourced sustainably from direct-trade farms, rotated weekly, roasted in Christchurch.",
    category: "drinks",
    tags: ["Vegan", "Vegetarian", "Gluten-Free", "Dairy-Free"],
    image: "/images/gallery_coffee.jpg",
  },
  {
    id: "dr2",
    name: "Elderflower Tonic",
    price: 9.50,
    description: "Town Tonic house elixir: cold-pressed elderflower, Canterbury lemon balm, sparkling spring tonic.",
    category: "drinks",
    tags: ["Vegan", "Vegetarian", "Gluten-Free", "Dairy-Free"],
    image: "/images/gallery_coffee.jpg",
  },
];

export default function MenuPage() {
  return (
    <div className="py-12 px-4 max-w-7xl mx-auto font-sans">
      <div className="text-center max-w-xl mx-auto mb-12">
        <h1 className="font-serif text-4xl md:text-6xl font-bold text-primary mb-3">Our Menu</h1>
        <p className="text-stone-600 text-sm">
          Canterbury ingredients prepared with care. We serve our All Day Menu from 8:00 am to 2:00 pm daily, refined dinners from 5:30 pm, and selected local drinks.
        </p>
      </div>

      <MenuExplorer items={MENU_ITEMS} />
    </div>
  );
}
